### PR TITLE
Add ruble sign (₽) to the Russian layout

### PR DESCRIPTION
**Pull request by soshial**
Screenshot_20221015-145455

### CODE REVIEW

**Comment by rkkr** [comment]
image

"₽" is only available in recent Android versions. This is in 4.4. You will see a blank symbol. And if someone send you a message with this symbol you'll also see a blank space or a square. There is a "₱" symbol in long-press "$" that is available in all Android versions.

**Comment by soshial** [comment]
Well, Android v4.4 was released more than 9 ears ago. Do you think we shouldn't add this symbol at all because it's not supported on the oldest version?

**Comment by rkkr** [comment]
It's not just 4.4, as I remember 5 also has limited UTF support. These two versions account for 12% of total user base.

**Comment by soshial** [comment]
Could you check it out, please, on Android 4.4 now?

**Comment by soshial** [comment]
@rkkr please have a look at the PR. I resolved the issue you mentioned.

**Comment by soshial** [comment]
@rkkr ?

**Comment by rkkr** [comment]
5.1 seems to work fine

**Pull request merged**
