### PR TITLE
Improve Settings Screens

### PR DESCRIPTION
**Pull request by wittmane**
This implements the suggestion I made in #263 to improve the settings screens. I won't reiterate the details here, but there are a few things that I think are worth calling out about this dev.

As I mentioned in the original issue, I decided to use simple names for the keyboard layouts in the settings screen. The generic layouts (qwerty, dvorak, etc) use the already defined display name. Languages that have only one layout (other than the generic layouts) just use the name of the language. The only locales that I'm aware of that have multiple non-generic keyboards are Bulgarian, Hindi, and Nepali. All of those have two layouts, and one is normally displayed as \<language\> (\<term\>), so I just simplified it to \<term\>. I noticed that the "BDS" in Bulgarian (BDS) was marked as not translated, which doesn't make sense since Bulgarian uses the Cyrillic alphabet, so I looked up what it's named in Bulgarian and marked that as translatable. While I was doing that I saw the other layout referred to as "phonetic". I imagine there is probably a more descriptive name for the other two as well, but I don't know enough about them to feel confident making that change. Similarly, I imagine there is a better name for the other non-generic layouts, especially ones like `nordic` that are used for multiple languages but are being named to match the language. Again, I didn't name them better because I don't know enough. Someone can always improve these later if it seems necessary (it should be easy updating the one function). Just using the language name should still be clear enough at least for now. I also added special handling around `serbian_qwertz` to have it display as "Serbian (Latin)" instead of just "Serbian", even though the `serbian` is grouped under a different locale (so they wouldn't be on the same page), but it seems confusing to have both display with the same name when they refer to different layouts.

I added a preference group with a title in the single language settings screen to show the name of the language. Since at least some versions of Android don't show the name of the parent setting and most languages that use generic layouts look the same, it might be unclear what language is being viewed, either when switching between apps or in the case of a misclick, so I added the title to help make it more clear.

One thing that might not be obvious or potentially controversial is the sort order of the languages. I noticed the system subtype settings screen shows the languages alphabetically, except that the current language and country are sorted first. For example in an English (US) locale, English (US) is before English (India), and both are before Afrikaans. I didn't see any documentation on it, so I can't guarantee that this sort order is always the case, but it seems like a decent sort order and it would be nice to be consistent (at least in some cases), so I did the same thing when listing the languages.

In the single language settings screen, I need to get the list of default subtypes (defined in method.xml). It seems a bit odd to me that I need to parse the xml manually, but I couldn't find a better way to load the contents of the file. One alternative that I had was that I could get the subtypes from the `InputMethodInfo` for this IME and filter out the custom subtypes from the preference. The sort order seems to be the same with this method, but I couldn't find any documentation guaranteeing it (this is the order that I'm showing the non-generic keyboard layouts in the single language screen). Also, just parsing the xml seems like a more straighforward solution. Because of those two reasons and that it still seemed fast enough (about 3.5ms vs 0.3ms when testing on my device, which is slower, but not noticeable), I decided to just parse the xml. I thought about caching it like some other things in `RichInputMethodManager`, but those get cleared too frequently when navigating between settings screens, so it wouldn't be helpful or this would have to be cleared at a different rate, which seems messy. Also, this is only used in the settings screen, so keeping it in memory doesn't really seem worth it since it doesn't seem like it will cause any noticeable performance issue.

Another thing that might seem a bit odd is when the custom subtypes are updated. It's done in `onPause`, rather than when clicking each switch preference. I did this so that if someone unchecks a subtype that was already enabled in the system, such as from a misclick, and then checks it again, the user isn't forced to re-enable it in the system. `onPause` was the latest time that I'm aware of that we can use to set the preference before the user might go to the system subtype settings screen and will need the custom subtypes created.

Also, I improved the plus button to add a new language (previously used to add a new subtype). It used to be white, which was fine on some older versions of Android that used a dark action bar, but at least on some versions of Android the action bar is light, making the button almost invisible. I changed the button to match the color of the text in the action bar. My solution for getting the text color seems a bit hacky, but I don't think it should cause problems. If it can't find the text view, it just won't do anything. Worst case scenario is probably that it somehow finds the wrong text view with text color that is the same as the background color of the action bar, but that's basically current behavior, so this doesn't seem like a real concern.

Another minor enhancement I added was that I disable the "switch to other keyboards" preference when "hide language switch key" is set since the preference would have no effect.

### CODE REVIEW

**Comment by rkkr** [comment]
> One alternative that I had was that I could get the subtypes from the InputMethodInfo for this IME and filter out the custom subtypes from the preference.

Raw XML files should not be read. For enabled subtypes `InputMethodInfo` is used. I don't know if it lists all available not enabled subtypes, but if it does- it should be used.

**Comment by rkkr** [comment]
The flow of enabling a new language is too strange. This is what happens now:
1. The list shows what you have enabled. That's nice.
2. Languages section has "Plus icon" and "Enable languages and Layouts" button.
  a. First confusion which one to click to enable a language.
3. You click a Plus icon.
4. Select a Language. All good so far. Picks Lithuanian.
5. Available layouts are shown. I want QWERTZ, I don't want to add QWERTY also, why can't I unselect it. These should be buttons like in the Language list as we're adding a language/layout.
6. Selected QWERTZ, now what? There is no Done button. Going back resets.
7. Clicking "Some layouts still need to be enabled" takes you to the old input selection dialog and you need to find what you wanted to add.

If we're going this route, then the system "Languages" selection dialog has to be removed. It has bugs since ~Android 10 so I prefer it being thrown out.
It should be a "click add to add a new layout flow". GBoard uses a wizard with multiple Activitites for a long time now. FlorisBoard uses a single popup with dropdown. Both options are good as long as at the end of that flow you don't end up in the old language selection dialog. You should be able to find how to enable the layouts programmatically in FlorisBoard code (it's in Kotlin, but APIs are still the same).

Clicking a language in "Languages" section has to allow you to remove it (as we're going away from system Language selection dialog) and optionally change/add/remove layouts. Eventually we could move settings like "Number row" into here in case you only want it in a single language.

**Comment by wittmane** [comment]
Ok. I'll work on removing the system subtype selection dialog. That's a significant change, so it might take a bit before I finish it (I originally wrote up the issue to try to avoid needing large changes like this now, but I guess that didn't work). I personally like the multiple subtypes because I like being able to see all of the subtypes from all of my installed keyboards in the popup to change the active keyboard. It's somewhat similar to how the language key could switch between all of the subtypes of all of the keyboards, but as you mentioned earlier, Gboard doesn't do that now and most people don't want that. I guess if there are bugs with it and other keyboards like Gboard and FlorisBoard have moved away from having multiple subtypes in the system, managing them virtually is probably fine for us too.

Gboard has its own dialog to select a specific subtype when longpressing the language switch key. Is that something you think we need to have too, or should I leave that as a potential enhancement for later? FlorisBoard doesn't seem to have it, but it's in alpha, so using it as a reference for what features we could skip might not be super useful.

Since we won't have the system subtype screen to need to be consistent with, do you think the sort order of the languages I currently have is still good, or do you think it would be better to just sort them alphabetically? Similarly, how should we sort the generic keyboard layouts? Since we currently have default subtypes, I kept the default one at the top, but now if there are no defaults, what should we do? We could still define the default for languages and keep it at the top, but that might be a bit odd to have the generic keyboard layouts change order depending on the language, so my opinion would be to just have all languages display them in the same order.

Your comment about reading the XML is probably not directly relevant anymore since I'll be removing the multiple subtypes in the system to manage them virtually. I'll see what FlorisBoard does as a reference, but I won't be able to get the content from `InputMethodInfo` anymore, but I can probably move the contents of method.xml somewhere else that doesn't require parsing an XML file.

**Comment by rkkr** [comment]
> try to avoid needing large changes like this now
I can merge the rest of the settings changes except the Language section. They look fine.

> see all of the subtypes from all of my installed keyboards
I haven't thought about this. I would also prefer that all subtypes are still listed, but probably that is only settable thru the system Language selection dialog. Both Florisboard and GBoard don't expose their subtypes. But that will probably end up being "a new normal". Storing all the selected subtypes internally and adjusting the selection dialogs will be a huge change. If system inputs can be set programmatically that would be the preferred intermediate option.

> Gboard has its own dialog to select a specific subtype when longpressing the language switch key. Is that something you think we need to have too?
Definitely not for now.

> do you think the sort order of the languages I currently have is still good, or do you think it would be better to just sort them alphabetically?
Just sort alphabetically. No need to be smart.

> Since we currently have default subtypes, I kept the default one at the top, but now if there are no defaults, what should we do?
Default layout for a language still exists. Default language should be current OS language. Or is this about something else?

> move the contents of method.xml somewhere else
That will be required. method.xml will probably need to have some "languageless" input method defined so system would know that it's a keyboard, but not what layouts it supports. Actual layouts would go somewhere else. FlorisBoard should have the same.

**Comment by wittmane** [comment]
I reverted my changes to enabling subtypes. I'll work on that part as a separate PR.

> If system inputs can be set programmatically that would be the preferred intermediate option.

I agree that this would be preferred, but I'm not sure that it's possible. I tried looking into this before, but I didn't find a way to do it. If you want to look into it and end up finding a solution, let me know, and I'll happily enable the subtypes programmatically, but at least for now I'll move forward planning to manage them virtually.

The default subtype that I was referring to is different from the default language. For example, Czech uses qwertz by default and to enable qwerty, you need to add the custom input style in the preference. My question was if we should list these generic layouts in a different order depending on the language. In the Czech language screen, should we list qwertz first because it is the most likely choice for Czech users or should qwerty be first so that all languages' screens are consistent? Regardless of the sort order, we can still default to qwertz when the system language is Czech.

**Comment by rkkr** [comment]
> In the Czech language screen, should we list qwertz first?

GBoard shows the default layout for your language first and we should do the same if it's doable easily.

> If system inputs can be set programmatically that would be the preferred intermediate option.
I agree that this would be preferred, but I'm not sure that it's possible.

Probably not possible as all apps that have their own selector don't expose the language list to system.

I'll try to merge this PR this weekend.

**Pull request merged**
