### PR TITLE
Added additional actions on the keys when swiping out.

### PR DESCRIPTION
**Pull request by animeslave**
I liked the TouchPal keyboard behavior with swipes. And really wanted something like that, but on a another keyboard app. I like the idea of Simple Keyboard. Therefore, I decided to try to add it myself. At the same time practice programming on Android.

At the moment I set up swipes down and up. But it is possible to use swipes in other directions.

I could not understand how to change the preview image of the key. But maybe I understand how to do it later.

Swipe Actions

Sorry for my english, it's not my main language.

### CODE REVIEW

**Comment by licaon-kter** [comment]
It does what on swipes?

**Comment by animeslave** [comment]
On up swipe is typing capitalized character. 
On down swipe is typing symbol from hint of key.

**Comment by rkkr** [comment]
Swiping left/right/up/down is reserved for selection of other keys. If you swipe up from v and release on g, it should type g. Long-press on a key is also more intuitive than swipe down.

**Comment by animeslave** [comment]
> Swiping left/right/up/down is reserved for selection of other keys.

If you meaning a choosing in more keys menu, it is working fine with and without my option. I also added a option to off that feature.


>  If you swipe up from v and release on g, it should type g.

In my opinion it is not good behaviour, because without sliding (glide gesture) input like GBoard or Swype it is causes miss-clicks. Specially if you fast enough to type. And swipes helps to type faster. 

But I do not insist. I want add more features later.

**Pull request closed without merging**
