### PR TITLE
Possibility of undoing deletion by swiping backspace

### LINKED ISSUE #87: Swipe delete should be reversible
While swipe deleting, its easy to delete too many symbols. It would be nice to be able to swipe backwards, and have the deleted symbols reappear.
The delete buffer could be discarded once the finger is lifted.

Edit: Perhaps it would be easier and more userfriendly to select the characters while swipe deleting. The selected text would then be deleted on finger release.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Tested in emulators with API 23 and 27, probably needs some test for backwards compatibility.

Fixes #87.

----
<a class="imgpatreon" href="https://www.patreon.com/emmanuelmess" target="_blank">
Become a patreon</a>

### CODE REVIEW

**Comment by rkkr** [comment]
image

If we want to do it, then we should probably do the way it's done in GBoard. Text should be highlighted and deleted on release. This will also be tricky for apps that don't support text selection.

**Comment by EmmanuelMess** [comment]
> This will also be tricky for apps that don't support text selection.

Can we know if an a` doesn't support selection?

**Comment by rkkr** [comment]
I haven't checked but there should be a way. Some also don't provide the text before cursor, nor provide the cursor index. I have reverted space swipe based on index due to that.

**Comment by EmmanuelMess** [comment]
> I haven't checked but there should be a way.

I think what I have implemented should be used in cases where text can't be highlighted, and the GBoard method should be used when text can be highlighted. if the app/EditText doesn't provide the text before cursor, nor provide the cursor index we can't do anything. Sounds ok?

**Comment by EmmanuelMess** [comment]
@rkkr How can I get the TextView that is being edited?

**Comment by rkkr** [comment]
`setSelection()`, `getTextBeforeCursor()` and a few other methods from `InputConnection` is all you have. You probably won't get direct access to a TextView

**Comment by EmmanuelMess** [comment]
Implemented as in GBoard, I still have a small problem, if selected text is deleted, some other characters before the cursor are deleted too.

**Comment by rkkr** [comment]
Code looks good. Can you give more details/step-by-step about the "small problem"?

**Comment by EmmanuelMess** [comment]
> Code looks good. Can you give more details/step-by-step about the "small problem"?

Maybe it wasn't ready to be pulled, yet. Select text in the middle of a sentence, delete, and more than the selected text gets deleted.

**Comment by rkkr** [comment]
Works fine in Chrome. What app are you testing in? There are apps that don't provide correct selection indexes, like Google Docs, but it worked fine when I tried.

**Comment by EmmanuelMess** [comment]
> Works fine in Chrome. What app are you testing in? There are apps that don't provide correct selection indexes, like Google Docs, but it worked fine when I tried.

KISS launcher.

**Comment by rkkr** [comment]
Works fine even on KISS. However I did find two issues. If position is
moved by clicking on text and then delete is swiped, then it only moves the
pointer untill the selection icon dissapears. The second is that in Gmail
random text is deleted. This looks like the text index issue.

**Comment by EmmanuelMess** [comment]
> If position is
moved by clicking on text and then delete is swiped, then it only moves the
pointer untill the selection icon dissapears. The second is that in Gmail
random text is deleted. This looks like the text index issue.

We should have automatic tests for this.

**Comment by rkkr** [comment]
As these are the issues in the applications that don't provode correct
positions, there isn't much to test automatically.

As for gmail you can take a very long email, click reply and delete some
text at the bottom. What happens is that it selects ~2 lines of text just
by moving by one chararcter.

My initial space swipe inplementation used indexes and it was a similar
result. Will test and debug a bit more.

**Comment by rkkr** [comment]
It looks like I managed to workaround it. Please test 38ddb6972a66d39ac50c2ed25504e4a6fbba4834 .

As expected the current position pointer usually can't be trusted.

**Comment by EmmanuelMess** [comment]
@rkkr Nope, will try to make a video of the bug.

**Comment by ChristianKurz** [comment]
Works great, thank you! :+1:

**Pull request merged**
