### PR TITLE
Revamped layout for Bengali (Bangladesh)

### PR DESCRIPTION
**Pull request by RHJihan**
The previously added was wrongly named 'Bijoy'. Its name is Unijoy from where it is derived.
The Bijoy is a copyrighted layout. Its alternative layout with an open license is Unijoy.
This PR corrected that and added the proper license (in this commit https://github.com/rkkr/simple-keyboard/commit/a0cbd805f83907f1f9a923467f28a9b4e2f674e2).

Additional changes:
- Number row: Now number row items will be retrieved from KeyboardTextsTable. Each language (bn also) will get native numerals. (additional_morekeys_symbols) https://github.com/rkkr/simple-keyboard/commit/3506c1206f8cb5495edc16d0f242e6bcf3169abc
- Added Bengali spacing and punctuations https://github.com/rkkr/simple-keyboard/commit/6f09b6a6afae40a4bf9c28533ef2691c39d95851
- updated KeyboardTextsTable for bn https://github.com/rkkr/simple-keyboard/commit/69f46a4164e12fbd8f76fd625f77443ede4254b0
- set the unijoy layout as no auto-cap https://github.com/rkkr/simple-keyboard/commit/698cc4de73dd7be8e3c6ac278b696552c695807b

This PR also set Unijoy as the default layout for bn_BD and set Akkhor as a subtype. As most of the people in Bangladesh use the Unijoy layout. Very few (nearly zero) people use the Akkhor layout.

### CODE REVIEW

**Comment by rkkr** [comment]
Unijoy license is GPL, which is more strict than the current project Apache license. It's probably fine for current application (not sure if root license file requires updates), but this might complicate the forks as it forbids close sourcing it.

**Comment by RHJihan** [comment]
When I wrote the layout xml based on the m17n database, I simply put the GPL license head from there. So I guess now I can change it simply to Apache.

**Comment by RHJihan** [comment]
When I wrote the layout xml based on the m17n database, I simply put the GPL license head from there. So I guess now I can change it simply to Apache.
I used this layout in a different keyboard project of mine [here](https://github.com/OtobiCorp/OtobiKeyboard/blob/master/app/src/main/res/xml/rowkeys_bengali_otobi1.xml). This Unijoy layout is derived from there. Even the previous Bijoy xml was derived from there as per [this comment](https://github.com/rkkr/simple-keyboard/pull/362#issuecomment-1256916206).

[m17n/m17n-db.git](http://git.savannah.gnu.org/cgit/m17n/m17n-db.git/commit/NEWS?id=5fe5d4baf00fe729274684334fba1607a68ff699), [The m17n Library](https://www.nongnu.org/m17n/manual-en/m17nDBData.html)

**Comment by rkkr** [comment]
https://www.drinkvvines.com/wp/wp-content/plugins/superstorefinder-wp/images/icons/sec4/1.txt/usr/share/m17n/bn-unijoy.mim

Well what you wrote isn't a modification of "bn-unijoy.mim", but you wrote it from scratch. So my guess is you can put whatever license on it (a change to Apache should be fine). You wouldn't be able to throw someones license out if it was a "derivative work".

There is a second block here: copyright. You can't throw this one out as it looks at "what it does". So add the original copyrights back, which will not block anything just like most of the the other code is a googles copyright.

**Comment by RHJihan** [comment]
Though I wrote the xml based on the bn-unijoy.mim, I guess the _mim file itself_ is under the GPL, not the letter combination of the layout. 

> There is a second block here: copyright. You can't throw this one out as it looks at "what it does". So add the original copyrights back, which will not block anything just like most of the the other code is a googles copyright.

So, are you suggesting reverting the license commit?

**Comment by rkkr** [comment]
Nope, as you wrote yourself GPL doesn't prevent you from implementing a similar thing from scratch. But the copyright does, so this is not correct as google doesn't own the copyright for UniJoy:
```
Copyright 2020, The Android Open Source Project
```

It just needs to be replaced with:
```
** Copyright (C) 2005, 2008
**   National Institute of Advanced Industrial Science and Technology (AIST)
**   Registration Number H15PRO112
```

You will also find in the source code a few files (that I wrote from scratch) that have my copyright.

**Comment by RHJihan** [comment]
updated

**Comment by fahimscirex** [comment]
@RHJihan it would be great if you can add probhat.

**Pull request merged**
