### PR TITLE
Change buttons color to neutral (Return button and other)

### PR DESCRIPTION
**Pull request by MikeWent**
## TL;DR
I've improved the appearance of the Return button without breaking the hardware acceleration.

See this [issue](https://github.com/rkkr/simple-keyboard/issues/92).

### Convert all icons to graysacle colorspace, removing all unnecessary colors
```bash
cd app/src/main/res
find drawable* -type f -name "sym*" -exec convert {} -channel ARGB -matte -colorspace gray {} \;
```

### Generate missing Return button icons for light themes

Create `make_dark_icon.sh`:
```bash
#!/bin/bash
image="$1"
final_path="${image::len-8}light.png"
convert $image +level-colors "#00000000","#44444499" $final_path
```
Allow execution
```bash
chmod +x make_dark_icon.sh
```
Run
```bash
find drawable* -type f \( -name "sym_keyboard_return_lxx_dark.png" -o -name "sym_keyboard_search_lxx_dark.png" -o -name "sym_keyboard_send_lxx_dark.png" -o -name "sym_keyboard_done_lxx_dark.png" -o -name "sym_keyboard_go_lxx_dark.png" -o -name "sym_keyboard_next_lxx_dark.png" -o -name "sym_keyboard_previous_lxx_dark.png" \) -exec ./make_dark_icon.sh {} \;
```

### Edit corresponding .xml files

See commit

### CODE REVIEW

**Comment by MikeWent** [comment]
Screenshots of new UI:
Material Light
Material Light Bordered
Material Dark
Material Dark Bordered

**Comment by rkkr** [comment]
1. Enter button still needs to have a border in borderless themes. At least for me it looks weird. Majority of keyboards highlight the action key. This is also probably done because contents of it changes.
2. Icons can't be converted to gray-scale. Things like shift lock are indicated by color.
3. White return button icons color differs from other white keys. It is visible when they have the same background.

**Comment by MikeWent** [comment]
> 1. Enter button still needs to have a border in borderless themes. At least for me it looks weird. Majority of keyboards highlight the action key. This is probably done because contents of it changes.

The button has border in bordered theme and doesn't have border in non-bordered theme. This is logically correct.

iOS 12.3.1 keyboard

On iOS, for example, Return button is rendered the same way as all functional keys. 

So why should Enter be _always_ highlighted? The corresponding icon on the Return button indicates its action anyway.

> 2. Icons can't be converted to gray-scale. Things like shift lock are indicated by color.

Shift mode
Caps mode

Both Shift and Caps modes are indicated by uppercase letters all over the keyboard and Caps mode also has indication via Shift button background. Is there really any need in colors?

> 3. White return button icons color differs from other white keys

Fixed with recent commit [3ca23ed](https://github.com/rkkr/simple-keyboard/pull/120/commits/3ca23ed1c6ca1467d327a16c091c642b03a5b694), see screenshots above.

**Comment by rkkr** [comment]
> 1. Enter button still needs to have a border

Does iOS have a borderless theme where enter key is without a border? I've looked thru other keyboards on play store (it's a mess), and looks like the only keyboard that has borderless action key without highlighting is SwiftKey. The default approach for borderless theme is an action key with border. Another option (Minuum) is to put colors on icons, but that is done for all action keys (don't like it).

There won't be an option that makes everyone happy. Unless you put an option for that in the settings. I'm not against using the same background as in other action keys (it doesn't have to be green). This will also simplify the icon set. I won't merge if default behavior (action key border) is changed.

 > 2. Icons can't be converted to gray-scale. Things like shift lock are indicated by color.

It shows which key caused the case change and that Shift mode was manually/automatically changed and you can switch it back as a reflex. This is also used across keyboards. A color is shown only for the first character in the sentence, so you shouldn't worry too much. Again, won't merge a change in default behavior.

**Comment by Wilker-a** [comment]
this [removing color of enter/confirm button] can simply be an opt-in setting, while the default button background could have a softer background color

**Comment by rkkr** [comment]
I can do it this way if you agree:
- I'll cherry-pick the part with action key background same as other keys
- Borderless action key border STAYS the same neutral color as borded theme

This change can be released. Later we can work on adding the setting to hide the border.

Agreed?

**Comment by MikeWent** [comment]
I agree, but have one note about the 3rd point:
> Shift icon color (and others) stay

What about changing teal (green) color to white (and dark gray for light themes)? These colors are neutral and are not theme specific, allowing users to use the keyboard with any system/app theme.

**Comment by MikeWent** [comment]
There is an APK with my commited improvements:

https://storage.meew.me/s/z8SkKx9XNMSypZQ

MD5: 2321eb4c9b78b7d2d42c8ed4fd3a753e
SHA256: 6c9c1ce89593a9418d9a3485182731438dc425bb83298d0a02a830f5217c735d

**Pull request closed without merging**
