### PR TITLE
Bengali subtype keyboard layout (Bijoy)

### PR DESCRIPTION
**Pull request by iamrasel**
This PR contains the subtype keyboard layout for Bengali language (Bangladesh). I hope everything is okay to be merged.

<table><tr>
<td></td>
<td></td>
<td></td>
</tr></table>

### CODE REVIEW

**Comment by rkkr** [comment]
Is there are reference that I could use for checking validity?

The format is `Language (Region)`.

In GBoard I don't see such `Bengali (Bangladesh)` combination. There's only:
- Bangla (Bangladesh)
- Various languages (Bengali)

Also as this is a new language (not a new layout of existing language), it should be added as a new language, not as a layout for `Bangla (Bangladesh)`.

**Comment by iamrasel** [comment]
Bangla or Bengali, both are the same language, [reference](https://en.wikipedia.org/wiki/Bengali_language). Different place, different language name; but there is no structural difference. So, `Bengali (Bangladesh)` and `Bangla (Bangladesh)`, both are equal.

> Is there are reference that I could use for checking validity?

[This](https://f-droid.org/en/packages/io.github.otobikb.inputmethod.latin/) is a Bangla/Bengali keyboard available in F-droid.

Simple Keyboard already has a layout for Bengali/Bangla (Bangladesh) language - _Akkhor_, but this layout is not so popular to us. Most of us use _Bijoy_ layout on pc/android, so I added this one.

**Comment by rkkr** [comment]
If it's a layout for an existing language, then it should be a subtype. Look how Turkish Q is setup.

**Comment by rkkr** [comment]
...and it looks setup that way. I'll retest in weekend.

**Comment by iamrasel** [comment]
Yes, it's a subtype. And I followed the pull request for Turkish Q layout while doing this. Except, I added the main punctuation mark and the number row for our bn language.

**Comment by iamrasel** [comment]
You can see tha changes in the screenshots I provided above.

**Pull request merged**
