### PR TITLE
Enable white navigation bar for bright keyboard colors

### PR DESCRIPTION
**Pull request by milaq**
Also respects user defined keyboard background color.

Android 8 or newer required (SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR).

### CODE REVIEW

**Comment by rkkr** [comment]
This won't work on Samsung S series. By default LatinIME sets the navigation color to Black, which caused the 3 button icons to turn White (as if background was Black), but the navigation bar color stays White. Which ended up with White buttons on White background. I had to remove this code block: https://github.com/rkkr/simple-keyboard/commit/0273499ad247512575f3867b52be4efaba2cf4aa .

In Samsung the navigation bar color changes between apps, so the OS somehow chooses the color, but that is probably based on the application theme. Or it only allows the application (not the keyboard) to set the color. I can't test as I don't own a Samsung S.

**Comment by rkkr** [comment]
I'm also not sure about the look of how this will end up. Having a black navigation bar + bright keyboard + bright app isn't bad. The navigation bar is at the bottom of the screen, so it being black, it looks not part of the screen.
Now if you have a grey keyboard and a white navigation bar (brighter than the keyboard), that would look weird. I don't know if it's allowed, but having the navigation bar the same color as the keyboard would make more sense.
Again, I don't want to touch the navigation bar due to how it works in some phones. This would need to be enabled by a user setting.

**Comment by milaq** [comment]
It looks rather coherent. The keyboard looks more integrated into the UI with a matching navigation bar color.
Most modern keyboards also do this.

I agree that this maybe needs an 'advanced settings; toggle. Not only to avoid issues with it, but also give people the opportunity to turn it off.

I'll have a look at it and update the PR asap.

**Comment by milaq** [comment]
See above commit for user setting.

Cheers

**Comment by rkkr** [comment]
I've probably merged too soon. The code as it is now will break Samsung S series as even if setting is disabled, `window.setNavigationBarColor(Color.BLACK);` will put white buttons on white background.

I've tried to move the check for `mUseMatchingNavbarColor` earlier so that nothing would be called if it's disabled, but then it's impossible to switch off the matching color, as system remembers the last used color. I need to set the original color to revert it, but there is no way to know what that was.

**Comment by milaq** [comment]
I'll have a look at it.

Maybe we can invoke a navbar redraw on setting changes.

**Comment by rkkr** [comment]
effe6f49b8d4fae958a39ccbe9ad6189509226c7

This seems to work on the emulator. I have no idea what will happen in Samsung after `getNavigationBarColor` and `setNavigationBarColor` calls.

**Comment by milaq** [comment]
Setting the navigation bar color without setting the flags is ill-advised.
See https://github.com/rkkr/simple-keyboard/commit/effe6f49b8d4fae958a39ccbe9ad6189509226c7#diff-6064a774fc85066280117b1f7041a0adR1102
You will be getting an issue with Oreo where the background color will be set but not the flags. Thus having a black on black navbar.
We need to always set the bgcolor and flags together or we will run into issues.

While the above works, this may create a cornercase where the user changes the navbar color after enabling the setting in simple-keyboard. Thus the original settings will be the wrong values.

Additionally, to work around Samsung's hacky attempts at coloring the navbar I think we should find a way to reset the decor view on the navbar setting changes to let SystemUI handle the coloring anew.
We should only be setting the navbar if the setting is enabled. We must not touch it if the user disables it, but just reset the view. I'll have a look at it.

As a dirty workaround, force-stopping and restarting the keyboard should also clear those color flags.

**Comment by rkkr** [comment]
I'm aware that just setting the background color and not updating the button color can end up in a bad combination, but if that is disables by default, I'm not so concerned. If you use a dark theme, you can still use it. Otherwise that can be gated to Android P as before.

As for resetting the original, what I have pushed is the best I could think of and I don't know if it's good enough.

**Pull request merged**
