### PR TITLE
Added debug activity with suitable EditText

### PR DESCRIPTION
**Pull request by EmmanuelMess**

### CODE REVIEW

**Comment by rkkr** [comment]
If truly needed, this should be a separate application.

**Comment by EmmanuelMess** [comment]
>  this should be a separate application.

Why? The activity in this PR isn't compiled for release, just for debug. 
If we put another app we'll end up having to install two apps, and then launching it to test and debug; with an Activity we can just set up the Run Configuration to start the activity automatically.

**Comment by EmmanuelMess** [comment]
@rkkr ping?

**Comment by rkkr** [comment]
Will not merge. This activity is still compiled for release, it's just not included in the manifest. Even with minification enabled, adding the appcompat dependencies increases the size to 1,6MB. Also this doesn't help much as you can just leave an app open like Chrome and install new keyboard APK versions without even closing the activity.

**Pull request closed without merging**
