### PR TITLE
Change the layout and backspace behavior to match Swiftkey

### PR DESCRIPTION
**Pull request by DonnieWest**
It's unlikely that you actually want this, but, I wanted to offer it regardless. This behavior helps swiftkey refugees like myself :)

### CODE REVIEW

**Comment by rkkr** [comment]
I don't like the layout change. And to make sure how the delete is expected to work: _all word is deleted if delete is pressed 4 times_?

**Comment by DonnieWest** [comment]
All of the word is deleted if delete is held down. I make sure there is a delay though - the part you're looking at skips deletion unless delete has been held down for a bit

**Comment by DonnieWest** [comment]
And yeah, no worries if you don't like it  :-)

I was just seeing if this would be helpful to _someone_ :-P

**Comment by rkkr** [comment]
If it works as you described and all word is deleted after holding down long enough for 4 characters to get deleted, then this may be a feature worth adding. I'll need to test it a bit to check how it feels.

**Pull request closed without merging**
