### PR TITLE
Manage subtypes virtually

### PR DESCRIPTION
**Pull request by wittmane**
This implements the second half of the improvements I suggested in #263 to allow enabling alternate keyboard layouts more easily. Based on the discussion in #270, this requires managing subtypes internally rather than through the system. The general workflow for enabling languages/layouts is mostly the same as I originally proposed, except now it doesn't open the system subtype settings page and adding a new language is always done using the plus button. Also, I updated the new language popup to allow selecting multiple to easily enable multiple languages quickly to avoid a degradation from current functionality. When multiple are selected, it just enables the default subtype and doesn't open the individual language settings page.

For managing subtypes virtually, there are two ways to switch subtypes: the language switch key to move to the next subtype and long pressing the language switch key or spacebar to open a dialog to pick a subtype directly.

For switching to the next subtype, I tried to match roughly what current functionality seems to be. Rather than having a fixed order to move through subtypes, whenever a subtype is used, it gets moved to the top of the list. For users with three or more subtypes enabled, I assume the most common use would be that they type in one language, switch to another for a bit, and then switch back to the first. This allows them to quickly back without needing to iterate through all of the other subtypes to get back to the first. Also, if switching to other IMEs is enabled, this allows all of the subtypes to be iterated through before moving to a different IME, regardless of which subtype is currently being used.

Instead of a long press on the language switch key and spacebar opening the system's IME picker, if there are multiple subtypes enabled, it will open a new dialog to directly select the subtypes for this IME.

---

Misc notes or other minor changes:

I noticed that additional layouts for `sr_ZZ` (`Serbian (Latin)`) previously displayed custom input styles as `Serbian (Dvorak)` rather than `Serbian (Latin) (Dvorak)`, which seems misleading, so I fixed it. 

The language on spacebar didn't display for implicitly enabled subtypes. Implicitly enabled isn't really a feature anymore (there is an initial default but that's slightly different) and this doesn't seem like a useful feature, so now the language shows up whenever there is more than one subtype.

There was some handling for `Locale.forLanguageTag("sr-Latn")`. I'm not sure how we could have found a `InputMethodSubtype` with that language tag, so maybe I don't fully understand what it was for, but I don't think it's relevant anymore after all the changes, so I don't have any similar handling for it.

Esperanto uses the `spanish` layout, but unlike the other locales that use `spanish`, it doesn't allow generic layouts. That seems a bit odd, but I didn't change functionality.

`RichInputMethodManager::switchToNextInputMethod` had some fallback code in case `InputMethodManager::switchToNextInputMethod` isn't available for ICS (SDK 15) or earlier, which is less than the min SDK for this project, so that isn't relevant, and I removed it.

The settings key used to open a dialog to open either the settings activity or the system subtype settings activity. Now that the system subtype settings isn't used, this dialog seems unnecessary. Now the key just opens the settings activity directly. Editing the enabled languages is a click away from the main settings page, so showing a dialog to allow jumping directly there wouldn't save any time for someone wanting to edit the languages, and it would just add a click for someone wanting to edit other settings.

For automatically switching to a subtype for a certain locale, there was some handling for a `MSG_SWITCH_LANGUAGE_AUTOMATICALLY` message. I couldn't figure out what this was for, but it doesn't seem necessary. My best guess is that it's related to some timing issue with getting the token from the window, which isn't necessary for the virtual subtypes. I couldn't figure out how to get it to break without it (and without my changes), so maybe it's a rare timing issue, I don't actually know what to test, or it isn't actually necessary (regardless of my changes). I decided to just remove it to simplify things since it doesn't seem to be necessary.

There was a crash in the preferences setting screen because the type for the checkbox/switch preference changes depending on the version of Android for some reason, so I fixed that.

### CODE REVIEW

**Comment by rkkr** [comment]
Things we'll probably need to resolve before public availability:
- Long-press space and language key should show all input methods. You must be able to select other keyboard from there. GBoard allows it. Will check FlorisBoard.
- Ability to add multiple languages at once is unnecessary and inconsistent with flow of adding a single language.
- Back button in layout selection dialog is not intuitive when adding a new language.
- Removal of the language is not intuitive.
- Language list with all config should move from `.java` to `resources`.

More things will probably come with more testing. But hey, it works :+1:

**Comment by wittmane** [comment]
> Long-press space and language key should show all input methods. You must be able to select other keyboard from there. GBoard allows it. Will check FlorisBoard.

I didn't realize Gboard did this, but it seems reasonable to do. I'll start working on this. FlorisBoard seems to just show the system picker.

> Back button in layout selection dialog is not intuitive when adding a new language.
> Removal of the language is not intuitive.

Do you have suggestions for what would be better? I don't like how Gboard uses cancel/done buttons. Everything else in Simple Keyboard's settings app saves as you make changes (other than popups), so I think confirmation buttons would be weird and could lead to accidentally losing a change when using the back button. For adding a new language, if the default layout wasn't initially selected, do you think that would be more clear that checking a layout enables it immediately and the back button will just navigate to the previous page (not losing any changes)? If you think that change is intuitive enough, would removing languages also be intuitive as it's just the opposite of enabling the language, or do you still think something else should be done, such as a remove button either on the general or individual language page?

> Ability to add multiple languages at once is unnecessary and inconsistent with flow of adding a single language.

I agree that the flow is a bit different, but I want to make sure adding multiple languages isn't too much of a pain. One thing I don't like about Gboard is how slow it is to add multiple languages. Admittedly, my use case is mostly for enabling a bunch of things to quickly test or compare something, but I'm sure there are some people who have a more legitimate use for enabling more than two languages. When using the system's subtype settings, it would take 4 clicks to enable 2 additional languages, but now without being able to select multiple (and assuming I make the change to force the specific layout to be manually checked) it would take 8 clicks (and potentially a bit more scrolling). That isn't huge, but that difference increases with each additional language (assuming we're comparing enabling them all at one time and the default layout is used for each language). I'm fine with changing how enabling multiple quickly might be done if you have ideas (I'll try to come up with some improvement too), but I'd prefer to not just remove it entirely.

> Language list with all config should move from `.java` to `resources`.

Do you have an idea of how we should do that? In #270 you said we shouldn't read raw XML files, so I'm not sure how to get all of the details in resources without doing something like shoving it all into one array like `locale_and_extra_value_to_keyboard_layout_set_map` or splitting bits between multiple arrays like `predefined_layouts`, which both seem like terrible ways to manage it. Putting it in `.java` also probably allows more flexibility to simplify similar languages like I can with the switch case. I generally understand how organizing something like this could make sense with resources, but in this case, I don't see a benefit in doing this, and it seems like it would just make it worse.

**Comment by rkkr** [comment]
No normal user will enable 50 languages. It's only useful for debugging and testing. So I don't mind the amount of clicks. Normally you'll only do that once or twice.
Adding a new language is a wizard now, so it must end with a confirmation. Clicking back goes to the previous page and doesn't commit the action.
Removal could just be a "trash bin" icon in top right. GBoard deletion flow is weird as it took me 10+ seconds to find it.

**Comment by wittmane** [comment]
I can see how you would think of this as a wizard, but that isn't really what I was going for and is not how I think of it. For adding a new language, I could see adding a confirmation button, but when editing an existing language, I think it would be weird. I generally think that confirmation buttons in a settings app (other than in a popup) feel very out of place when everything else saves right as changes are made. If we add a confirmation button when adding a new language, it might seem slightly inconsistent if we didn't have a confirmation button when editing an existing language, although adding a confirmation button on the existing languages would seem inconsistent with the rest of the settings.

What would you think if I changed the flow to be more intentionally not a wizard? We could keep the multi-select for the languages and regardless of how many languages were selected, it would just add the default layout and stay on the main languages page. This would be more similar to the previous functionality. Instead of using the system's subtype settings page, it's an internal popup (only offering unused languages). Also, since most users probably just use the default layout, it doesn't force them to confirm something or move to the previous page. This still improves the previous functionality because modifying the keyboard layout for a language is in a better location and enabling the different layouts is much more convenient. It also creates a good place to put language specific settings if we want to add that.

**Comment by rkkr** [comment]
One more strange issue. After this change GBoard can't be disabled if there's only GBoard + Simple Keyboard enabled. Strangely SimpleKeyboard can be disabled in this case. FlorisBoard has the same issue. Reproducible in emulator.

For language add flow, I've already removed the multiselect and will add a Remove button in couple minutes.
One more option would be to have a "check icon" in the top-right corner in place of that remove icon as a confirmation. Many apps have it, even thou it's sometime not easily visible. Having auto-save in edit flow would have some difference in usability and code duplication, or we could have it always there. Maybe it's a compromise?

**Pull request merged**
